export const SET_DRIVERS = 'SET_DRIVERS';
export const DECREMENT_DRIVERS_PAGE_NUM = 'DECREMENT_DRIVERS_PAGE_NUM';
export const INCREMENT_DRIVERS_PAGE_NUM = 'INCREMENT_DRIVERS_PAGE_NUM';
export const SET_MAX_DRIVERS = 'SET_MAX_DRIVERS';
