export const DRIVERS_LOADING_TRUE = 'DRIVERS_LOADING_TRUE';
export const DRIVERS_LOADING_FALSE = 'DRIVERS_LOADING_FALSE';
export const RACES_LOADING_TRUE = 'RACES_LOADING_TRUE';
export const RACES_LOADING_FALSE = 'RACES_LOADING_FALSE';
