export const SET_RACES = 'SET_RACES';
export const SET_DRIVER_ID = 'SET_DRIVER_ID';
export const DECREMENT_RESULTS_PAGE_NUM = 'DECREMENT_RESULTS_PAGE_NUM';
export const INCREMENT_RESULTS_PAGE_NUM = 'INCREMENT_RESULTS_PAGE_NUM';
export const SET_MAX_RACES = 'SET_MAX_RACES';
