import { Driver } from './interfaces';

export const driversMock: Driver[] = [
  {
    driverId: 'ascari',
    url: 'http://en.wikipedia.org/wiki/Alberto_Ascari',
    givenName: 'Alberto',
    familyName: 'Ascari',
    dateOfBirth: '1918-07-13',
    nationality: 'Italian',
  },
  {
    driverId: 'ashdown',
    url: 'http://en.wikipedia.org/wiki/Peter_Ashdown',
    givenName: 'Peter',
    familyName: 'Ashdown',
    dateOfBirth: '1934-10-16',
    nationality: 'British',
  },
  {
    driverId: 'ashley',
    url: 'http://en.wikipedia.org/wiki/Ian_Ashley',
    givenName: 'Ian',
    familyName: 'Ashley',
    dateOfBirth: '1947-10-26',
    nationality: 'British',
  },
  {
    driverId: 'ashmore',
    url: 'http://en.wikipedia.org/wiki/Gerry_Ashmore',
    givenName: 'Gerry',
    familyName: 'Ashmore',
    dateOfBirth: '1936-07-25',
    nationality: 'British',
  },
  {
    driverId: 'aston',
    url: 'http://en.wikipedia.org/wiki/Bill_Aston',
    givenName: 'Bill',
    familyName: 'Aston',
    dateOfBirth: '1900-03-29',
    nationality: 'British',
  },
  {
    driverId: 'attwood',
    url: 'http://en.wikipedia.org/wiki/Richard_Attwood',
    givenName: 'Richard',
    familyName: 'Attwood',
    dateOfBirth: '1940-04-04',
    nationality: 'British',
  },
  {
    driverId: 'ayulo',
    url: 'http://en.wikipedia.org/wiki/Manny_Ayulo',
    givenName: 'Manny',
    familyName: 'Ayulo',
    dateOfBirth: '1921-10-20',
    nationality: 'American',
  },
  {
    driverId: 'badoer',
    code: 'BAD',
    url: 'http://en.wikipedia.org/wiki/Luca_Badoer',
    givenName: 'Luca',
    familyName: 'Badoer',
    dateOfBirth: '1971-01-25',
    nationality: 'Italian',
  },
  {
    driverId: 'baghetti',
    url: 'http://en.wikipedia.org/wiki/Giancarlo_Baghetti',
    givenName: 'Giancarlo',
    familyName: 'Baghetti',
    dateOfBirth: '1934-12-25',
    nationality: 'Italian',
  },
  {
    driverId: 'bailey',
    url: 'http://en.wikipedia.org/wiki/Julian_Bailey',
    givenName: 'Julian',
    familyName: 'Bailey',
    dateOfBirth: '1961-10-09',
    nationality: 'British',
  },
  {
    driverId: 'baldi',
    url: 'http://en.wikipedia.org/wiki/Mauro_Baldi',
    givenName: 'Mauro',
    familyName: 'Baldi',
    dateOfBirth: '1954-01-31',
    nationality: 'Italian',
  },
  {
    driverId: 'ball',
    url: 'http://en.wikipedia.org/wiki/Bobby_Ball_(auto_racer)',
    givenName: 'Bobby',
    familyName: 'Ball',
    dateOfBirth: '1925-08-26',
    nationality: 'American',
  },
  {
    driverId: 'balsa',
    url: 'http://en.wikipedia.org/wiki/Marcel_Balsa',
    givenName: 'Marcel',
    familyName: 'Balsa',
    dateOfBirth: '1909-01-01',
    nationality: 'French',
  },
  {
    driverId: 'bandini',
    url: 'http://en.wikipedia.org/wiki/Lorenzo_Bandini',
    givenName: 'Lorenzo',
    familyName: 'Bandini',
    dateOfBirth: '1935-12-21',
    nationality: 'Italian',
  },
  {
    driverId: 'banks',
    url: 'http://en.wikipedia.org/wiki/Henry_Banks',
    givenName: 'Henry',
    familyName: 'Banks',
    dateOfBirth: '1913-06-14',
    nationality: 'American',
  },
  {
    driverId: 'barbazza',
    url: 'http://en.wikipedia.org/wiki/Fabrizio_Barbazza',
    givenName: 'Fabrizio',
    familyName: 'Barbazza',
    dateOfBirth: '1963-04-02',
    nationality: 'Italian',
  },
  {
    driverId: 'barber',
    url: 'http://en.wikipedia.org/wiki/Skip_Barber',
    givenName: 'Skip',
    familyName: 'Barber',
    dateOfBirth: '1936-11-16',
    nationality: 'American',
  },
  {
    driverId: 'john_barber',
    url: 'http://en.wikipedia.org/wiki/John_Barber_(racing_driver)',
    givenName: 'John',
    familyName: 'Barber',
    dateOfBirth: '1929-07-22',
    nationality: 'British',
  },
  {
    driverId: 'barilla',
    url: 'http://en.wikipedia.org/wiki/Paolo_Barilla',
    givenName: 'Paolo',
    familyName: 'Barilla',
    dateOfBirth: '1961-04-20',
    nationality: 'Italian',
  },
  {
    driverId: 'barrichello',
    code: 'BAR',
    url: 'http://en.wikipedia.org/wiki/Rubens_Barrichello',
    givenName: 'Rubens',
    familyName: 'Barrichello',
    dateOfBirth: '1972-05-23',
    nationality: 'Brazilian',
  },
  {
    driverId: 'bartels',
    url: 'http://en.wikipedia.org/wiki/Michael_Bartels',
    givenName: 'Michael',
    familyName: 'Bartels',
    dateOfBirth: '1968-03-08',
    nationality: 'German',
  },
  {
    driverId: 'barth',
    url: 'http://en.wikipedia.org/wiki/Edgar_Barth',
    givenName: 'Edgar',
    familyName: 'Barth',
    dateOfBirth: '1917-01-26',
    nationality: 'German',
  },
  {
    driverId: 'bassi',
    url: 'http://en.wikipedia.org/wiki/Giorgio_Bassi',
    givenName: 'Giorgio',
    familyName: 'Bassi',
    dateOfBirth: '1934-01-20',
    nationality: 'Italian',
  },
  {
    driverId: 'bauer',
    url: 'http://en.wikipedia.org/wiki/Erwin_Bauer',
    givenName: 'Erwin',
    familyName: 'Bauer',
    dateOfBirth: '1912-07-17',
    nationality: 'German',
  },
  {
    driverId: 'baumgartner',
    url: 'http://en.wikipedia.org/wiki/Zsolt_Baumgartner',
    givenName: 'Zsolt',
    familyName: 'Baumgartner',
    dateOfBirth: '1981-01-01',
    nationality: 'Hungarian',
  },
  {
    driverId: 'bayol',
    url: 'http://en.wikipedia.org/wiki/%C3%89lie_Bayol',
    givenName: 'Élie',
    familyName: 'Bayol',
    dateOfBirth: '1914-02-28',
    nationality: 'French',
  },
  {
    driverId: 'beauman',
    url: 'http://en.wikipedia.org/wiki/Don_Beauman',
    givenName: 'Don',
    familyName: 'Beauman',
    dateOfBirth: '1928-07-26',
    nationality: 'British',
  },
  {
    driverId: 'bechem',
    url: 'http://en.wikipedia.org/wiki/G%C3%BCnther_Bechem',
    givenName: 'Günther',
    familyName: 'Bechem',
    dateOfBirth: '1921-12-21',
    nationality: 'German',
  },
  {
    driverId: 'behra',
    url: 'http://en.wikipedia.org/wiki/Jean_Behra',
    givenName: 'Jean',
    familyName: 'Behra',
    dateOfBirth: '1921-02-16',
    nationality: 'French',
  },
  {
    driverId: 'bell',
    url: 'http://en.wikipedia.org/wiki/Derek_Bell_(auto_racer)',
    givenName: 'Derek',
    familyName: 'Bell',
    dateOfBirth: '1941-10-31',
    nationality: 'British',
  },
];
